import{test,expect} from '@playwright/test'
test("automation",async({page})=>{
    await page.goto('https://demoqa.com/automation-practice-form')
    await page.getByPlaceholder('First Name').fill('preetham')
    await page.getByPlaceholder('Last Name').fill('sai')
    await page.getByPlaceholder('name@example.com').fill('kpreetham834@gmail.com')
    await page.locator('[value="Male"]').check()
    await expect(page.locator('[value="Male"]')).toBeChecked()
    await expect(page.locator('[value="Female"]')).not.toBeChecked()
    await page.getByPlaceholder('Mobile Number').fill('7396341425')
    await page.locator('#dateOfBirthInput').fill('2004-03-08')
    await page.locator('[class="react-datepicker__month-select"]').selectOption('March')
    await page.locator('[class="react-datepicker__year-select"]').selectOption('2004')
    await page.getByLabel('Choose Monday, March 8th, 2004').click()
    await page.locator('[class="subjects-auto-complete__input-container css-19bb58m"]').click()
    await page.locator('#subjectsInput').fill('Math')
    await page.locator('[class="subjects-auto-complete__menu css-1nmdiq5-menu"]',{hasText:'Maths'}).click()
    await expect(page.locator('.subjects-auto-complete__multi-value')).toHaveText('Maths')
    await page.getByLabel('Sports').check()
    await expect(page.locator('#hobbies-checkbox-1')).toBeChecked()
    await page.getByPlaceholder('Current Address').fill('6-1-159/402')
    await page.getByPlaceholder('Select State').click()
    await page.locator()
})